version: "2.2"

services:

  storage-account:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: storage-account
    restart: always
    command: "azurite --blobHost 0.0.0.0 --blobPort 20003 --queueHost 0.0.0.0 --queuePort 20004 --tableHost 0.0.0.0 --tablePort 20005"
    ports:
      - "20003:20003"
      - "20004:20004"
      - "20005:20005"
    networks:
       - poc-be

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - poc-be

  enqueue-ms:
    depends_on:
      - rabbitmq
    container_name: enqueue-ms
    restart: always
    build:
      context: ./enqueue-ms
      dockerfile: Dockerfile
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    env_file:
      - ./enqueue-ms/.dockerenv
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: ["yarn", "start"]
    networks:
      - poc-be

  scout-ms:
    depends_on:
      - rabbitmq
      - storage-account
    container_name: scout-ms
    restart: always
    build:
      context: ./scout-ms
      dockerfile: Dockerfile
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    env_file:
      - ./scout-ms/.dockerenv
    expose:
      - "3001"
    ports:
      - "3001:3001"
    command: ["yarn", "start"]
    networks:
      - poc-be
  
  # load-test:
  #   depends_on:
  #     - rabbitmq
  #     - storage-account
  #     - scout-ms
  #     - enqueue-ms
  #   container_name: load-test
  #   links:
  #     - enqueue-ms:api.localhost
  #   build:
  #     context: ./load-test
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./load-test/.dockerenv
  #   command: run /dist/bulk_document.js
  #   networks:
  #     - poc-be

volumes:
  certs:
    driver: local

networks:
  poc-be:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450